env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "halium"

task:
  persistent_worker:
  name: halium 10.0 Ubuntu Touch (UBPorts)

  info_script:
    - lscpu
  Build_boot_script:
    - cd /home/doraemon/HDD/CI/roms/halium/boot/10
    - export ANDROID_MAJOR_VERSION=q
    - export PLATFORM_VERSION=10
    - rm -rf deviceinfo
    - cp -r deviceinfo-on7xelte deviceinfo
    - ./build.sh -b workdir
    - ./build/fetch-and-prepare-latest-ota.sh "16.04/arm64/android9/stable" on7xelte ota
    - ./build/system-image-from-ota.sh ota/ubuntu_command out
    - rm -rf deviceinfo
